#!/usr/bin/env python3
"""examples/, generated from the runs rather than written.

Six examples: the course from brief to rollback, and the five refusals, each
from the engine that owns it. Each holds what went in and what came out, and
for a refusal what came out is the artifact the repair loop acts on: an unsat
core, a named rule, a leak path, a proof tree, a violated formula.

What went into an engine is recorded by wrapping the engine's own entry point
while the scene runs, so an example cannot show an input the scene did not use.

    python tools_examples.py           rewrite examples/
    python tools_examples.py --check   fail if examples/ is not what the runs produce
"""
from __future__ import annotations

import contextlib
import io
import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).parent
sys.path.insert(0, str(ROOT))

import tests.conftest  # noqa: E402,F401  the credential sink, as for any run without LIVE=1
from engines.datalog import engine as datalog  # noqa: E402
from engines.opa import engine as opa  # noqa: E402
from engines.prolog import engine as prolog  # noqa: E402
from engines.temporal import engine as temporal  # noqa: E402
from engines.z3 import engine as z3engine  # noqa: E402
from scenarios import refusals, run, walkthrough as w  # noqa: E402

OUT = ROOT / "examples"

# One per refusal scene: the folder, the engine call the scene makes, and the
# names of that call's arguments, in order.
REFUSALS = [
    ("02-a-brief-that-cannot-be-satisfied", refusals.unsatisfiable_brief,
     z3engine, "check", ["brief", "thresholds"]),
    ("03-an-audience-the-author-was-not-granted", refusals.audience_not_granted,
     opa, "check", ["action", "actor", "brief", "state", "policy_data"]),
    ("04-a-node-citing-a-source-its-audience-cannot-see", refusals.restricted_source,
     datalog, "check_permission_leak", ["nodes", "articles", "audience", "visibility"]),
    ("05-an-objective-nothing-approved-covers", refusals.objective_not_covered,
     prolog, "check_coverage", ["course", "objectives", "nodes", "develops"]),
    ("06-a-course-published-with-a-stale-node", refusals.published_with_a_stale_node,
     temporal, "check", ["trace"]),
]


def _plain(value):
    """What YAML and JSON can hold: tuples become lists, anything else its text."""
    return json.loads(json.dumps(value, default=str))


def _yaml(value) -> str:
    return yaml.safe_dump(_plain(value), sort_keys=False, allow_unicode=True, width=100)


@contextlib.contextmanager
def _recording(module, name: str, into: list):
    original = getattr(module, name)

    def recorded(*args, **kwargs):
        into.append((args, kwargs))
        return original(*args, **kwargs)

    setattr(module, name, recorded)
    try:
        yield
    finally:
        setattr(module, name, original)


def course() -> dict[str, str]:
    p = run.the_course()
    run.after_publication(p)
    m = p.machine
    stages = "".join(f"stage {n:>2} {name:<26} {subject:<22} {result}\n"
                     for n, name, subject, result in p.stages)
    verdict = temporal.check(m.trace())
    outcome = {"revisions": {r.id: r.state for r in m.store.revisions.values()},
               "live_pointer": m.store.live_pointer,
               "trace_steps": len(m.trace()),
               "invariants": "every invariant holds" if verdict.ok else verdict.refusal.summary}
    return {"input.yaml": _yaml({"brief": w.BRIEF, "actor": run.AUTHOR}),
            "stages.txt": stages,
            "outcome.yaml": _yaml(outcome),
            "trace.json": json.dumps(_plain(m.trace()), indent=1) + "\n"}


def refusal(scene, module, name: str, params: list[str]) -> tuple[dict[str, str], object]:
    calls: list = []
    with _recording(module, name, calls):
        verdict = scene()
    if verdict.ok or len(calls) != 1:
        raise SystemExit(f"{scene.__name__}: expected one refused call, got {len(calls)} and ok={verdict.ok}")
    args, kwargs = calls[0]
    given = {**dict(zip(params, args)), **kwargs}
    r = verdict.refusal
    out = {"engine": r.engine, "kind": r.kind, "summary": r.summary, "detail": r.detail}
    if name == "check" and module is temporal:
        # The whole trace goes in; the step the formula fails on is what to read.
        trace = given.pop("trace")
        files = {"trace.json": json.dumps(_plain(trace), indent=1) + "\n"}
        given["trace"] = f"trace.json — {len(trace)} steps, the run of scenarios/legal_run.py " \
                         f"with one node stale at PublishRequested"
    else:
        files = {}
    return {"input.yaml": _yaml(given), "refusal.yaml": _yaml(out), **files}, r


def readme(rows: list[tuple[str, str, str, str]]) -> str:
    lines = ["# Examples", "",
             "Generated by `make examples` from the same runs as `make run` and `make refusals`.",
             "Do not edit by hand: CI regenerates them and fails if they differ.", "",
             "| example | refused by | artifact | what comes back |", "|---|---|---|---|"]
    lines += [f"| [`{folder}`]({folder}/) | {engine} | {kind} | {summary} |"
              for folder, engine, kind, summary in rows]
    lines += ["", "`01` is the happy path through the gateway: `input.yaml` is the brief (the model's "
              "and the guardrail's answers are the recording in `scenarios/cassette.py`), `stages.txt` "
              "the gateway's stages in order, `outcome.yaml` where every revision ended, and "
              "`trace.json` the trace the invariants were checked on.", "",
              "`02`–`06` each hold `input.yaml`, exactly what the engine was given, and "
              "`refusal.yaml`, what it gave back. The artifact in `detail` is what a repair acts on."]
    return "\n".join(lines) + "\n"


def build() -> dict[str, str]:
    files = {f"01-a-course-published-and-rolled-back/{k}": v for k, v in course().items()}
    rows = [("01-a-course-published-and-rolled-back", "—", "trace", "published, revised, rolled back; "
             "every invariant holds")]
    for folder, scene, module, name, params in REFUSALS:
        out, r = refusal(scene, module, name, params)
        files.update({f"{folder}/{k}": v for k, v in out.items()})
        rows.append((folder, r.engine, r.kind, r.summary.replace("|", "\\|")))
    files["README.md"] = readme(rows)
    return files


def main(argv: list[str]) -> int:
    with contextlib.redirect_stdout(io.StringIO()):
        files = build()
    on_disk = {str(p.relative_to(OUT)): p.read_text(encoding="utf-8")
               for p in OUT.rglob("*") if p.is_file()} if OUT.exists() else {}
    if "--check" in argv:
        if on_disk != files:
            stale = sorted(k for k in files.keys() | on_disk.keys() if files.get(k) != on_disk.get(k))
            print(f"examples/ is stale ({', '.join(stale)}): run make examples and commit it")
            return 1
        print(f"examples/ is current: {len(files)} files")
        return 0
    for stale in on_disk.keys() - files.keys():
        (OUT / stale).unlink()
    for path, text in files.items():
        (OUT / path).parent.mkdir(parents=True, exist_ok=True)
        (OUT / path).write_text(text, encoding="utf-8")
    print(f"wrote {len(files)} files under examples/")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
